const data = {
    PREFECTURE: [
        { value: 1, display: '北海道' },
        { value: 2, display: '青森県' },
        { value: 3, display: '岩手県' },
        { value: 4, display: '宮城県' },
        { value: 5, display: '秋田県' },
        { value: 6, display: '山形県' },
        { value: 7, display: '福島県' },
        { value: 8, display: '茨城県' },
        { value: 9, display: '栃木県' },
        { value: 10, display: '群馬県' },
        { value: 11, display: '埼玉県' },
        { value: 12, display: '千葉県' },
        { value: 13, display: '東京都' },
        { value: 14, display: '神奈川県' },
        { value: 15, display: '新潟県' },
        { value: 16, display: '富山県' },
        { value: 17, display: '石川県' },
        { value: 18, display: '福井県' },
        { value: 19, display: '山梨県' },
        { value: 20, display: '長野県' },
        { value: 21, display: '岐阜県' },
        { value: 22, display: '静岡県' },
        { value: 23, display: '愛知県' },
        { value: 24, display: '三重県' },
        { value: 25, display: '滋賀県' },
        { value: 26, display: '京都府' },
        { value: 27, display: '大阪府' },
        { value: 28, display: '兵庫県' },
        { value: 29, display: '奈良県' },
        { value: 30, display: '和歌山県' },
        { value: 31, display: '鳥取県' },
        { value: 32, display: '島根県' },
        { value: 33, display: '岡山県' },
        { value: 34, display: '広島県' },
        { value: 35, display: '山口県' },
        { value: 36, display: '徳島県' },
        { value: 37, display: '香川県' },
        { value: 38, display: '愛媛県' },
        { value: 39, display: '高知県' },
        { value: 40, display: '福岡県' },
        { value: 41, display: '佐賀県' },
        { value: 42, display: '長崎県' },
        { value: 43, display: '熊本県' },
        { value: 44, display: '大分県' },
        { value: 45, display: '宮崎県' },
        { value: 46, display: '鹿児島県' },
        { value: 47, display: '沖縄県' },
        { value: 48, display: '海外' },
    ],
};
module.exports = data;
